[package]
name = "nameless-enum"
version = "0.1.0"

[dependencies.serde]
version = "1.0"
optional = true

[features]
default = ["std"]

# stable
std = ["alloc"]
alloc = []

async = []

serde = ["dep:serde"]

# nightly
# specialization = []
fn_impls = ["nightly_internals"]

nightly_internals = []
